//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StHumberHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWaitTime
    {
        public int user_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> no_of_patients { get; set; }
        public Nullable<int> no_of_doctors { get; set; }
        public Nullable<int> avg_appointment_time { get; set; }
    }
}
